name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: mikeelaurente
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
            dist/github-contribution-grid-snake.svg?color_snake=#f48fb1&color_dots=#fce4ec,#f8bbd0,#f48fb1,#ec407a,#ad1457

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output